# Action to create tasks on a set schedule, from
# https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Daily recurring ticket
on:
  schedule:
    - cron: 0 1 * * *

jobs:
  create_issue:
    name: Create recurring ticket
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Test recurring ticket
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          assignees: "ryscher"
          labels: "Testing"
          title: "Test recurring ticket"
          body: |
            ### RECURRING: Some great ticket
            (created by `recurring_tasks.yml`)

            - [ ] Start the recording
            - [ ] Check-ins
            - [ ] Discussion points
            - [ ] Post the recording
                    
            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
