# Action to create tasks on a set schedule, from
# https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Quarterly recurring tickets
on:
  schedule:
    - cron: 0 1 1 1,4,7,10 *

jobs:
  create_issue:
    name: Salesforce sync ticket
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Recurring ticket
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "maintenance"
          title: "QUARTERLY: Sync journals with Salesforce"
          body: |
            (created by `recurring_tasks_quarterly.yml`)
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_issue2:
    name: Journal clean ticket
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Recurring ticket
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "maintenance"
          title: "QUARTERLY: Clean journals with asterisks"
          body: |
            (created by `recurring_tasks_quarterly.yml`)
	    See https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/apis/journals.md#cleaning-journal-names
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_issue3:
    name: Institution clean ticket
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Recurring ticket
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "maintenance"
          title: "QUARTERLY: Clean institutions with asterisks"
          body: |
            (created by `recurring_tasks_quarterly.yml`)
	    See See https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/technical_notes/affiliations.md#cleaning-affiliation-names
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_issue4:
    name: Gem update ticket
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Recurring ticket
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          labels: "maintenance"
          title: "QUARTERLY: Update gem dependencies"
          body: |
            (created by `recurring_tasks_quarterly.yml`)
          pinned: false
          close-previous: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

